# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testcover.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 543)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.schemaLabel = QtWidgets.QLabel(self.centralwidget)
        self.schemaLabel.setObjectName("schemaLabel")
        self.horizontalLayout_8.addWidget(self.schemaLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.editSchemaBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editSchemaBtn.setObjectName("editSchemaBtn")
        self.horizontalLayout_8.addWidget(self.editSchemaBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fdLabel = QtWidgets.QLabel(self.centralwidget)
        self.fdLabel.setObjectName("fdLabel")
        self.horizontalLayout_5.addWidget(self.fdLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.editFDBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editFDBtn.setObjectName("editFDBtn")
        self.horizontalLayout_5.addWidget(self.editFDBtn)
        self.clearFDBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearFDBtn.setObjectName("clearFDBtn")
        self.horizontalLayout_5.addWidget(self.clearFDBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.fdText = QtWidgets.QListView(self.centralwidget)
        self.fdText.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fdText.setObjectName("fdText")
        self.verticalLayout.addWidget(self.fdText)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mincoverLabel = QtWidgets.QLabel(self.centralwidget)
        self.mincoverLabel.setObjectName("mincoverLabel")
        self.horizontalLayout_6.addWidget(self.mincoverLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.editCoverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editCoverBtn.setObjectName("editCoverBtn")
        self.horizontalLayout_6.addWidget(self.editCoverBtn)
        self.clearCoverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearCoverBtn.setObjectName("clearCoverBtn")
        self.horizontalLayout_6.addWidget(self.clearCoverBtn)
        self.testCoverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.testCoverBtn.setObjectName("testCoverBtn")
        self.horizontalLayout_6.addWidget(self.testCoverBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.mincoverText = QtWidgets.QListView(self.centralwidget)
        self.mincoverText.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mincoverText.setObjectName("mincoverText")
        self.verticalLayout.addWidget(self.mincoverText)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.schemaLabel.setText(_translate("MainWindow", "Schema"))
        self.editSchemaBtn.setToolTip(_translate("MainWindow", "Edit Schema"))
        self.editSchemaBtn.setStatusTip(_translate("MainWindow", "Add/Remove attributes from current schema"))
        self.editSchemaBtn.setText(_translate("MainWindow", "Edit"))
        self.fdLabel.setText(_translate("MainWindow", "Functional Dependencies"))
        self.editFDBtn.setToolTip(_translate("MainWindow", "Edit FDs"))
        self.editFDBtn.setStatusTip(_translate("MainWindow", "Add/remove functional dependencies"))
        self.editFDBtn.setText(_translate("MainWindow", "Edit"))
        self.clearFDBtn.setToolTip(_translate("MainWindow", "Clear FDs"))
        self.clearFDBtn.setStatusTip(_translate("MainWindow", "Clear all functional dependencies"))
        self.clearFDBtn.setText(_translate("MainWindow", "Clear"))
        self.mincoverLabel.setText(_translate("MainWindow", "Minimal Cover"))
        self.editCoverBtn.setToolTip(_translate("MainWindow", "Edit cover"))
        self.editCoverBtn.setStatusTip(_translate("MainWindow", "Edit Minimal Cover"))
        self.editCoverBtn.setText(_translate("MainWindow", "Edit"))
        self.clearCoverBtn.setToolTip(_translate("MainWindow", "Clear cover"))
        self.clearCoverBtn.setStatusTip(_translate("MainWindow", "Clear FDs in Minimal Cover"))
        self.clearCoverBtn.setText(_translate("MainWindow", "Clear"))
        self.testCoverBtn.setToolTip(_translate("MainWindow", "Test cover"))
        self.testCoverBtn.setStatusTip(_translate("MainWindow", "Test the proposed minimal cover"))
        self.testCoverBtn.setText(_translate("MainWindow", "Test"))

