# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stacked_interface.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedwidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedwidget.setObjectName("stackedwidget")
        self.Page1 = QtWidgets.QWidget()
        self.Page1.setObjectName("Page1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Page1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.schemaLine_2 = QtWidgets.QLineEdit(self.Page1)
        self.schemaLine_2.setAcceptDrops(False)
        self.schemaLine_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.schemaLine_2.setReadOnly(True)
        self.schemaLine_2.setObjectName("schemaLine_2")
        self.gridLayout_4.addWidget(self.schemaLine_2, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.schemaLabel_2 = QtWidgets.QLabel(self.Page1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.schemaLabel_2.setFont(font)
        self.schemaLabel_2.setStyleSheet("")
        self.schemaLabel_2.setObjectName("schemaLabel_2")
        self.horizontalLayout_7.addWidget(self.schemaLabel_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.editSchemaBtn_2 = QtWidgets.QPushButton(self.Page1)
        self.editSchemaBtn_2.setObjectName("editSchemaBtn_2")
        self.horizontalLayout_7.addWidget(self.editSchemaBtn_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.mincoverText_2 = QtWidgets.QListView(self.Page1)
        self.mincoverText_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mincoverText_2.setObjectName("mincoverText_2")
        self.gridLayout_4.addWidget(self.mincoverText_2, 7, 0, 1, 1)
        self.fdText_2 = QtWidgets.QListView(self.Page1)
        self.fdText_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fdText_2.setObjectName("fdText_2")
        self.gridLayout_4.addWidget(self.fdText_2, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fdLabel_2 = QtWidgets.QLabel(self.Page1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.fdLabel_2.setFont(font)
        self.fdLabel_2.setStyleSheet("")
        self.fdLabel_2.setObjectName("fdLabel_2")
        self.horizontalLayout_8.addWidget(self.fdLabel_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.editFDBtn_2 = QtWidgets.QPushButton(self.Page1)
        self.editFDBtn_2.setObjectName("editFDBtn_2")
        self.horizontalLayout_8.addWidget(self.editFDBtn_2)
        self.splitBtn_2 = QtWidgets.QPushButton(self.Page1)
        self.splitBtn_2.setObjectName("splitBtn_2")
        self.horizontalLayout_8.addWidget(self.splitBtn_2)
        self.clearBtn_2 = QtWidgets.QPushButton(self.Page1)
        self.clearBtn_2.setObjectName("clearBtn_2")
        self.horizontalLayout_8.addWidget(self.clearBtn_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mincoverLabel_2 = QtWidgets.QLabel(self.Page1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.mincoverLabel_2.setFont(font)
        self.mincoverLabel_2.setStyleSheet("")
        self.mincoverLabel_2.setObjectName("mincoverLabel_2")
        self.horizontalLayout_3.addWidget(self.mincoverLabel_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.genBtn_2 = QtWidgets.QPushButton(self.Page1)
        self.genBtn_2.setStyleSheet("")
        self.genBtn_2.setObjectName("genBtn_2")
        self.horizontalLayout_3.addWidget(self.genBtn_2)
        self.saveBtn_2 = QtWidgets.QPushButton(self.Page1)
        self.saveBtn_2.setObjectName("saveBtn_2")
        self.horizontalLayout_3.addWidget(self.saveBtn_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 6, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.stackedwidget.addWidget(self.Page1)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mincoverLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.mincoverLabel.setFont(font)
        self.mincoverLabel.setStyleSheet("")
        self.mincoverLabel.setObjectName("mincoverLabel")
        self.horizontalLayout_2.addWidget(self.mincoverLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.genBtn = QtWidgets.QPushButton(self.widget)
        self.genBtn.setStyleSheet("")
        self.genBtn.setObjectName("genBtn")
        self.horizontalLayout_2.addWidget(self.genBtn)
        self.saveBtn = QtWidgets.QPushButton(self.widget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_2.addWidget(self.saveBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 5, 0, 1, 1)
        self.fdText = QtWidgets.QListView(self.widget)
        self.fdText.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fdText.setObjectName("fdText")
        self.gridLayout_2.addWidget(self.fdText, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fdLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.fdLabel.setFont(font)
        self.fdLabel.setStyleSheet("")
        self.fdLabel.setObjectName("fdLabel")
        self.horizontalLayout_6.addWidget(self.fdLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.editFDBtn = QtWidgets.QPushButton(self.widget)
        self.editFDBtn.setObjectName("editFDBtn")
        self.horizontalLayout_6.addWidget(self.editFDBtn)
        self.clearBtn = QtWidgets.QPushButton(self.widget)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout_6.addWidget(self.clearBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.schemaLine = QtWidgets.QLineEdit(self.widget)
        self.schemaLine.setAcceptDrops(False)
        self.schemaLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.schemaLine.setReadOnly(True)
        self.schemaLine.setObjectName("schemaLine")
        self.gridLayout_2.addWidget(self.schemaLine, 2, 0, 1, 1)
        self.mincoverText = QtWidgets.QListView(self.widget)
        self.mincoverText.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mincoverText.setObjectName("mincoverText")
        self.gridLayout_2.addWidget(self.mincoverText, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.schemaLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.schemaLabel.setFont(font)
        self.schemaLabel.setStyleSheet("")
        self.schemaLabel.setObjectName("schemaLabel")
        self.horizontalLayout_5.addWidget(self.schemaLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.editSchemaBtn = QtWidgets.QPushButton(self.widget)
        self.editSchemaBtn.setObjectName("editSchemaBtn")
        self.horizontalLayout_5.addWidget(self.editSchemaBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.widget)
        self.stackedwidget.addWidget(self.page)
        self.horizontalLayout.addWidget(self.stackedwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedwidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.schemaLabel_2.setText(_translate("MainWindow", "Schema"))
        self.editSchemaBtn_2.setToolTip(_translate("MainWindow", "Edit Schema"))
        self.editSchemaBtn_2.setStatusTip(_translate("MainWindow", "Add/Remove attributes from schema"))
        self.editSchemaBtn_2.setText(_translate("MainWindow", "Edit"))
        self.fdLabel_2.setText(_translate("MainWindow", "Functional Dependencies"))
        self.editFDBtn_2.setToolTip(_translate("MainWindow", "Edit FDs"))
        self.editFDBtn_2.setStatusTip(_translate("MainWindow", "Add/Remove functional dependencies"))
        self.editFDBtn_2.setText(_translate("MainWindow", "Edit"))
        self.splitBtn_2.setToolTip(_translate("MainWindow", "Split RHS"))
        self.splitBtn_2.setStatusTip(_translate("MainWindow", "Simplify FDs by splitting RHS"))
        self.splitBtn_2.setText(_translate("MainWindow", "Split RHS"))
        self.clearBtn_2.setToolTip(_translate("MainWindow", "Clear FDs"))
        self.clearBtn_2.setStatusTip(_translate("MainWindow", "Clear all functional dependencies"))
        self.clearBtn_2.setText(_translate("MainWindow", "Clear"))
        self.mincoverLabel_2.setText(_translate("MainWindow", "Minimal Cover"))
        self.genBtn_2.setToolTip(_translate("MainWindow", "Generate"))
        self.genBtn_2.setStatusTip(_translate("MainWindow", "Generate a minimal cover from the FDs"))
        self.genBtn_2.setText(_translate("MainWindow", "Generate Cover"))
        self.saveBtn_2.setToolTip(_translate("MainWindow", "Export"))
        self.saveBtn_2.setStatusTip(_translate("MainWindow", "Export minimal cover to file in comma-separated format"))
        self.saveBtn_2.setText(_translate("MainWindow", "Export..."))
        self.mincoverLabel.setText(_translate("MainWindow", "Minimal Cover"))
        self.pushButton.setToolTip(_translate("MainWindow", "Edit cover"))
        self.pushButton.setStatusTip(_translate("MainWindow", "Edit the minimal cover"))
        self.pushButton.setText(_translate("MainWindow", "Edit"))
        self.genBtn.setToolTip(_translate("MainWindow", "Clear cover"))
        self.genBtn.setStatusTip(_translate("MainWindow", "Clear FDs from the minimal cover"))
        self.genBtn.setText(_translate("MainWindow", "Clear"))
        self.saveBtn.setToolTip(_translate("MainWindow", "Test cover"))
        self.saveBtn.setStatusTip(_translate("MainWindow", "Test the proposed minimal cover"))
        self.saveBtn.setText(_translate("MainWindow", "Test"))
        self.fdLabel.setText(_translate("MainWindow", "Functional Dependencies"))
        self.editFDBtn.setToolTip(_translate("MainWindow", "Edit FDs"))
        self.editFDBtn.setStatusTip(_translate("MainWindow", "Add/Remove functional dependencies"))
        self.editFDBtn.setText(_translate("MainWindow", "Edit"))
        self.clearBtn.setToolTip(_translate("MainWindow", "Clear FDs"))
        self.clearBtn.setStatusTip(_translate("MainWindow", "Clear all functional dependencies"))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.schemaLabel.setText(_translate("MainWindow", "Schema"))
        self.editSchemaBtn.setToolTip(_translate("MainWindow", "Edit Schema"))
        self.editSchemaBtn.setStatusTip(_translate("MainWindow", "Add/Remove attributes from schema"))
        self.editSchemaBtn.setText(_translate("MainWindow", "Edit"))

